[package]
name = "mmd"
version = "0.1.0"
authors = ["aankor <lambdasound@yandex.ru>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
encoding = "0.2"
fallible-iterator = "0.2"
enumflags2 = "0.6.0"
itertools = "0.8.0"
